const projects={ "soc-investigation":{title:"SOC Investigation",summary:"A hands-on phishing investigation performed in a TryHackMe SOC simulator environment, focused on correlating email, firewall and network evidence to determine whether suspicious activity represented a real security incident.",what:"A simulated SOC investigation involving a phishing email containing a malicious URL and a subsequent attempted connection from an internal host.",why:"To practice the investigative workflow used by security analysts when responding to suspicious activity and to develop the ability to reason from evidence rather than isolated alerts.",objective:"Identify the relevant indicators, reconstruct the activity, investigate the suspicious destination, determine the appropriate alert classification and document the findings.",tools:["SIEM","Email Logs","Firewall Logs","Threat Intelligence","IOC Analysis","TryHackMe SOC Simulator"],actions:["Analyzed email and firewall log data using SIEM information.","Reviewed the suspicious URL and associated destination information.","Correlated events across multiple log sources to identify a potential attack chain.","Identified relevant indicators of compromise associated with the activity.","Considered whether the evidence supported a True Positive or False Positive classification.","Documented investigation findings, limitations, escalation reasoning and recommended remediation actions."],skills:["Alert Triage","SIEM Investigation","Log Correlation","Phishing Analysis","IOC Identification","Threat Intelligence","Incident Documentation"],outcome:"Completed the investigation workflow and developed practical experience moving from an initial suspicious alert toward an evidence-based classification and documented response.",relevance:"This type of investigation reflects core SOC analyst activities: reviewing alerts, correlating evidence, identifying indicators, validating suspicious behavior, documenting conclusions and escalating when appropriate."}};

const header=document.querySelector(".site-header"),menuToggle=document.getElementById("menuToggle"),navLinks=document.getElementById("navLinks"),modal=document.getElementById("projectModal"),modalClose=document.getElementById("modalClose"),toast=document.getElementById("toast"),toastMessage=document.getElementById("toastMessage"),year=document.getElementById("year");
if(year)year.textContent=new Date().getFullYear();
function updateHeader(){if(header)header.classList.toggle("scrolled",window.scrollY>30)}window.addEventListener("scroll",updateHeader,{passive:true});updateHeader();
if(menuToggle&&navLinks){menuToggle.addEventListener("click",()=>{const open=navLinks.classList.toggle("active");menuToggle.setAttribute("aria-expanded",String(open))});navLinks.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{navLinks.classList.remove("active");menuToggle.setAttribute("aria-expanded","false")}))}
function tag(text){const e=document.createElement("span");e.textContent=text;return e}
function openProject(id){const p=projects[id];if(!p)return;modalTitle.textContent=p.title;modalSummary.textContent=p.summary;modalWhat.textContent=p.what;modalWhy.textContent=p.why;modalObjective.textContent=p.objective;modalOutcome.textContent=p.outcome;modalRelevance.textContent=p.relevance;modalTools.innerHTML="";p.tools.forEach(x=>modalTools.appendChild(tag(x)));modalSkills.innerHTML="";p.skills.forEach(x=>modalSkills.appendChild(tag(x)));modalActions.innerHTML="";p.actions.forEach(x=>{const li=document.createElement("li");li.textContent=x;modalActions.appendChild(li)});modal.classList.add("active");modal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");modalClose.focus()}
function closeProject(){modal.classList.remove("active");modal.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open")}
document.querySelectorAll("[data-project]").forEach(b=>b.addEventListener("click",()=>openProject(b.dataset.project)));
modalClose.addEventListener("click",closeProject);document.querySelectorAll("[data-close-modal]").forEach(x=>x.addEventListener("click",closeProject));document.addEventListener("keydown",e=>{if(e.key==="Escape"&&modal.classList.contains("active"))closeProject()});
let toastTimer;function showToast(msg){toastMessage.textContent=msg;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),3200)}
document.querySelectorAll("[data-placeholder],a[href='#']").forEach(e=>e.addEventListener("click",ev=>{const href=e.getAttribute("href");if(href&&href!=="#")return;ev.preventDefault();showToast(e.dataset.placeholder||"This evidence link has not been added yet.")}));
if("IntersectionObserver"in window){const observer=new IntersectionObserver((entries,o)=>entries.forEach(e=>{if(!e.isIntersecting)return;e.target.style.opacity="1";e.target.style.transform="none";o.unobserve(e.target)}),{threshold:.08});document.querySelectorAll(".about-grid,.skill-strip,.project-feature,.project-card,.empty-state,.learning-grid,.certification-card,.community-card,.contact-container").forEach(e=>{if(!matchMedia("(prefers-reduced-motion: reduce)").matches){e.style.opacity="0";e.style.transform="translateY(16px)";e.style.transition="opacity 600ms ease,transform 600ms ease"}observer.observe(e)})}
console.log("%cWilliam Arteaga — Cybersecurity Portfolio","color:#50e3b2;font-size:16px;font-weight:bold;");